import {
  Award,
  Brain,
  Calculator,
  CalendarDays,
  Crosshair,
  Dice5,
  Fish,
  Flame,
  GraduationCap,
  Hand,
  Layers,
  type LucideIcon,
  Medal,
  PartyPopper,
  Repeat,
  Spade,
  Sparkles,
  Swords,
  Target,
  Trophy,
  TrendingUp,
  Zap,
  Timer,
  Gauge,
  Grid3x3,
  Percent,
  CalendarCheck,
  Scale,
  Blocks,
  SlidersHorizontal,
  Cpu,
  Shield,
  Sigma,
  Eye,
  Waypoints,
  Users,
  Crown,
  Lightbulb,
  ScanEye,
  Radar,
  Ruler,
  GitFork,
  Binoculars,
  Bug,
  FlaskConical,
  ChartSpline,
  ListChecks,
  BadgeCheck,
  Route,
  Microscope,
} from "lucide-react";

/** Icons referenced by name from course data, drills and achievements. */
export const ICONS: Record<string, LucideIcon> = {
  spade: Spade,
  trophy: Trophy,
  layers: Layers,
  swords: Swords,
  hand: Hand,
  calculator: Calculator,
  crosshair: Crosshair,
  brain: Brain,
  medal: Medal,
  dice: Dice5,
  repeat: Repeat,
  target: Target,
  party: PartyPopper,
  sparkles: Sparkles,
  graduation: GraduationCap,
  flame: Flame,
  calendar: CalendarDays,
  award: Award,
  trending: TrendingUp,
  fish: Fish,
  zap: Zap,
  timer: Timer,
  gauge: Gauge,
  grid: Grid3x3,
  percent: Percent,
  "calendar-check": CalendarCheck,
  scale: Scale,
  blocks: Blocks,
  sliders: SlidersHorizontal,
  cpu: Cpu,
  shield: Shield,
  sigma: Sigma,
  eye: Eye,
  waypoints: Waypoints,
  users: Users,
  crown: Crown,
  lightbulb: Lightbulb,
  "scan-eye": ScanEye,
  radar: Radar,
  ruler: Ruler,
  "git-fork": GitFork,
  binoculars: Binoculars,
  bug: Bug,
  flask: FlaskConical,
  "chart-spline": ChartSpline,
  "list-checks": ListChecks,
  "badge-check": BadgeCheck,
  route: Route,
  microscope: Microscope,
};

export function NamedIcon({ name, size = 20, strokeWidth = 2 }: { name: string; size?: number; strokeWidth?: number }) {
  const Icon = ICONS[name] ?? Spade;
  return <Icon size={size} strokeWidth={strokeWidth} aria-hidden="true" />;
}
