export interface GlossaryEntry {
  term: string;
  definition: string;
}

/** Poker terms used across the course, alphabetical. */
export const GLOSSARY: GlossaryEntry[] = [
  { term: "3-bet", definition: "The first re-raise before the flop. The blinds count as the first bet and the open as the second." },
  { term: "4-bet", definition: "A re-raise of a 3-bet." },
  { term: "Aggression", definition: "Betting and raising rather than checking and calling. Aggression wins pots two ways: at showdown and when opponents fold." },
  { term: "All-in", definition: "Putting every chip you have in front of you into the pot." },
  { term: "Ante", definition: "A small forced bet from every player, common in later tournament levels. It adds dead money to the pot." },
  { term: "Backdoor draw", definition: "A draw that needs both the turn and the river, like three cards to a flush on the flop." },
  { term: "Bad beat", definition: "Losing a hand you were a big favorite to win." },
  { term: "Bankroll", definition: "Money set aside only for poker. Guidelines: 20–40 buy-ins for cash games, 100 or more for tournaments." },
  { term: "Big blind (BB)", definition: "The larger forced bet, posted two seats left of the button. Stacks and bets are often measured in big blinds." },
  { term: "Blocker", definition: "A card in your hand that makes certain opponent hands less likely. Holding the A♥ means no one else has the ace-high heart flush." },
  { term: "Bluff", definition: "A bet or raise with a weak hand that aims to make better hands fold." },
  { term: "Bluff-catcher", definition: "A hand that beats only bluffs. Calling with one is right when villain bluffs often enough for the price." },
  { term: "Board", definition: "The shared community cards: flop, turn and river." },
  { term: "Bubble", definition: "The last elimination before the paid places in a tournament." },
  { term: "Button (BTN)", definition: "The dealer position. It acts last after the flop, which makes it the most profitable seat." },
  { term: "bb/100", definition: "Big blinds won per 100 hands: the standard measure of a cash-game win rate." },
  { term: "C-bet", definition: "A continuation bet: the preflop raiser betting again on the flop." },
  { term: "Calling station", definition: "A player who calls too often and rarely folds. Value bet them and don't bluff." },
  { term: "Capped range", definition: "A range missing its strongest hands, usually because the player would have raised them earlier." },
  { term: "Check-raise", definition: "Checking, then raising after an opponent bets." },
  { term: "Coin flip", definition: "A roughly 50/50 all-in, like a pair against two higher cards." },
  { term: "Combo", definition: "One specific two-card holding. A pair has 6 combos, a suited hand 4 and an offsuit hand 12." },
  { term: "Condensed range", definition: "A range made mostly of medium-strength hands, with few very strong hands or bluffs." },
  { term: "Cutoff (CO)", definition: "The seat to the right of the button." },
  { term: "Donk bet", definition: "Betting into the preflop raiser from out of position on a new street, instead of checking to them." },
  { term: "Dominated hand", definition: "A hand that shares a card with a better one, like KJ against KQ. It wins rarely and loses big pots." },
  { term: "Draw", definition: "A hand that needs more cards to become strong, like four to a flush." },
  { term: "Dry board", definition: "A board with few possible draws, like K♠ 7♦ 2♣." },
  { term: "Effective stack", definition: "The smaller of the two stacks in a hand: the most either player can win or lose." },
  { term: "Equity", definition: "Your share of the pot on average if all the cards were dealt out, based on how often you win." },
  { term: "EV (expected value)", definition: "The average result of a decision if you made it many times." },
  { term: "Flat call", definition: "Just calling a raise instead of re-raising." },
  { term: "Flop", definition: "The first three community cards." },
  { term: "Flush draw", definition: "Four cards of one suit, needing one more. It has 9 outs." },
  { term: "Fold equity", definition: "The value a bet or raise gains from the chance that opponents fold." },
  { term: "GTO", definition: "Game theory optimal: a balanced strategy that can't be exploited. Solvers approximate it; it's a baseline, not always the most profitable play against weak opponents." },
  { term: "Gutshot", definition: "An inside straight draw needing one specific rank. It has 4 outs." },
  { term: "Heads-up", definition: "A hand or game with only two players." },
  { term: "Hijack (HJ)", definition: "The seat two to the right of the button." },
  { term: "Hole cards", definition: "Your two private cards." },
  { term: "ICM", definition: "Independent Chip Model: converts tournament chip stacks into their share of the prize money." },
  { term: "Implied odds", definition: "Money you expect to win on later streets when you hit, beyond what's in the pot now." },
  { term: "In position (IP)", definition: "Acting after your opponent on each street after the flop." },
  { term: "Isolation raise", definition: "A raise over one or more limpers to play heads-up against them. Size it about 3 BB plus 1 BB per limper." },
  { term: "Kicker", definition: "The highest side card that breaks ties between hands of the same category." },
  { term: "LAG", definition: "Loose-aggressive: a player who plays many hands and plays them aggressively." },
  { term: "Limp", definition: "Just calling the big blind preflop instead of raising." },
  { term: "Linear range", definition: "A range of the best hands down to some cutoff, with no bluffs mixed in." },
  { term: "Maniac", definition: "A player who raises and bluffs constantly. Tighten up and let them bluff into your good hands." },
  { term: "MDF", definition: "Minimum defense frequency: pot ÷ (pot + bet). Continue with at least this share of your range or any two cards can bluff you." },
  { term: "Multiway pot", definition: "A pot with three or more players. Bluff less and bet mostly strong hands." },
  { term: "Nash equilibrium", definition: "Strategies where neither player can gain by changing theirs. The push/fold solver finds it for short stacks." },
  { term: "Nit", definition: "A very tight player who rarely bluffs. Steal their blinds and fold to their big bets." },
  { term: "Nut advantage", definition: "Having more of the very strongest hands than your opponent on a given board." },
  { term: "Nuts", definition: "The best possible hand on the current board." },
  { term: "Offsuit", definition: "Two starting cards of different suits, written with an o, like AKo." },
  { term: "Open raise", definition: "The first raise before the flop when everyone before you has folded." },
  { term: "Open-ended straight draw", definition: "Four cards in a row needing a card at either end. It has 8 outs." },
  { term: "Out of position (OOP)", definition: "Acting before your opponent after the flop." },
  { term: "Outs", definition: "Unseen cards that improve your hand to one that's likely best." },
  { term: "Overbet", definition: "A bet larger than the pot, used with a polarized range and a nut advantage." },
  { term: "Overcard", definition: "A card higher than any on the board, or higher than a pair." },
  { term: "Overpair", definition: "A pocket pair higher than every card on the board." },
  { term: "PFR", definition: "Preflop raise: how often a player raises before the flop." },
  { term: "Pocket pair", definition: "Two hole cards of the same rank." },
  { term: "Polarized range", definition: "A range of very strong hands and bluffs, with few medium hands." },
  { term: "Position", definition: "The order players act in. Acting later gives you more information." },
  { term: "Pot control", definition: "Keeping the pot small with a medium-strength hand, usually by checking." },
  { term: "Pot odds", definition: "The price of a call: call ÷ (pot + call). You need at least that much equity to call profitably." },
  { term: "Push/fold", definition: "Short-stack strategy where you either go all-in or fold, usually under about 10–15 BB." },
  { term: "Rainbow", definition: "A flop with three different suits, so no flush draw is possible yet." },
  { term: "Rake", definition: "The fee the house takes from each pot or tournament entry." },
  { term: "Range", definition: "All the hands a player could hold in a given spot." },
  { term: "Range advantage", definition: "Having the stronger range overall on a board, which lets you bet more often." },
  { term: "Reverse implied odds", definition: "When hitting your hand often still loses a big pot, as with dominated hands." },
  { term: "Risk premium", definition: "The extra equity ICM requires to call an all-in in a tournament, compared with chip odds." },
  { term: "River", definition: "The fifth and last community card." },
  { term: "Semi-bluff", definition: "A bet with a draw: it can win now if they fold or later if you hit." },
  { term: "Set", definition: "Three of a kind made with a pocket pair and one board card." },
  { term: "Set mining", definition: "Calling with a small pair mainly to flop a set. It needs deep stacks, roughly 15–20 times the call." },
  { term: "Showdown", definition: "Revealing hands after the last betting round to decide the winner." },
  { term: "Slowplay", definition: "Checking or calling with a very strong hand to trap. Usually worse than betting on wet boards." },
  { term: "Small blind (SB)", definition: "The smaller forced bet, posted directly left of the button." },
  { term: "SPR", definition: "Stack-to-pot ratio: effective stack ÷ pot. Low SPRs make top pair easy to commit with." },
  { term: "Squeeze", definition: "A 3-bet after an open raise and one or more callers." },
  { term: "Suited", definition: "Two starting cards of the same suit, written with an s, like AKs." },
  { term: "Suited connectors", definition: "Suited cards of consecutive ranks, like 9♥8♥. They make straights and flushes." },
  { term: "TAG", definition: "Tight-aggressive: a player who plays few hands and plays them aggressively." },
  { term: "Tell", definition: "A physical or timing habit that may reveal hand strength. Betting patterns are usually more reliable." },
  { term: "Thin value bet", definition: "A value bet that expects to be called by worse hands only slightly more often than by better ones." },
  { term: "Tilt", definition: "Playing worse because of emotion, often after bad beats." },
  { term: "Trips", definition: "Three of a kind made with one hole card and a pair on the board." },
  { term: "Turn", definition: "The fourth community card." },
  { term: "Under the gun (UTG)", definition: "The first seat to act before the flop, left of the big blind." },
  { term: "Value bet", definition: "A bet that wants to be called by worse hands." },
  { term: "Variance", definition: "Short-term swings in results around your long-run average." },
  { term: "VPIP", definition: "Voluntarily put money in pot: how often a player calls or raises before the flop." },
  { term: "Wet board", definition: "A board with many possible draws, like J♥ T♥ 9♣." },
  { term: "Wheel", definition: "The lowest straight, A-2-3-4-5, where the ace plays low." },
  { term: "Brick", definition: "A turn or river card that changes nothing: it completes no draws and pairs nothing important." },
  { term: "Card removal", definition: "How the cards you can see change the combos villain can hold. Also called blockers." },
  { term: "Committed", definition: "Having so much of your stack in the pot, compared with what is left, that folding would give up too much." },
  { term: "Initiative", definition: "Being the last player to bet or raise. The player with the initiative can often win the pot with a continuation bet." },
  { term: "Leak", definition: "A mistake a player repeats, which costs money over time." },
  { term: "Missed draw", definition: "A straight or flush draw that did not complete by the river. Missed draws are natural bluffs." },
  { term: "Results-oriented thinking", definition: "Judging a decision by how the hand turned out instead of by its expected value." },
  { term: "Stop-loss", definition: "A limit on how much you will lose in a session before you stop playing." },
];
