/**
 * Precomputes the preflop raiser's equity against the caller on every canonical
 * flop for each spot in FLOP_SPOTS, and writes src/poker/flopEquity.ts.
 *
 * Each flop samples SAMPLES deals: a compatible combo from each range and a random
 * turn and river. Standard error is about 0.5 / sqrt(SAMPLES).
 *
 * Run with: npm run build:flops
 */
import { writeFileSync } from "node:fs";
import { cpus } from "node:os";
import { resolve } from "node:path";
import { isMainThread, parentPort, Worker, workerData } from "node:worker_threads";
import { fileURLToPath } from "node:url";
import { CANONICAL_FLOPS, FLOP_SPOTS } from "../src/poker/flops";
import { encodeEquity } from "../src/poker/preflop";
import { FACING_SETS, OPENING_SETS } from "../src/poker/ranges";
import { rangeCombos, rangeVsRangeEquity } from "../src/poker/rangeTools";

const SAMPLES = Number(process.env.SAMPLES) || 20000;

function equity(spot: (typeof FLOP_SPOTS)[number], flopIndex: number): number {
  const flop = CANONICAL_FLOPS[flopIndex].cards;
  return rangeVsRangeEquity(
    rangeCombos(OPENING_SETS[spot.raiser], flop),
    rangeCombos(FACING_SETS[spot.facing].call, flop),
    flop,
    SAMPLES,
  );
}

if (isMainThread) {
  const workers = Math.max(1, cpus().length);
  const jobs: [number, number][] = [];
  FLOP_SPOTS.forEach((_, s) => CANONICAL_FLOPS.forEach((_, f) => jobs.push([s, f])));
  const tables = FLOP_SPOTS.map(() => new Float64Array(CANONICAL_FLOPS.length));
  const started = Date.now();
  let finished = 0;
  const self = fileURLToPath(import.meta.url);
  for (let w = 0; w < workers; w++) {
    const worker = new Worker(self, { workerData: jobs.filter((_, k) => k % workers === w) });
    worker.on("message", (results: [number, number, number][]) => {
      for (const [s, f, eq] of results) tables[s][f] = eq;
      if (++finished < workers) return;
      const entries = FLOP_SPOTS.map((spot, s) => `  "${spot.id}": "${Array.from(tables[s], encodeEquity).join("")}",`);
      const file = `// Generated by scripts/build-flop-equity.ts. Do not edit by hand.
// The preflop raiser's equity against the caller on each of the 1,755 canonical flops
// (CANONICAL_FLOPS order), ${SAMPLES} sampled deals each; two characters per value.
export const FLOP_EQUITY_SAMPLES = ${SAMPLES};
export const FLOP_EQUITY: Record<string, string> = {
${entries.join("\n")}
};
`;
      writeFileSync(resolve(process.cwd(), "src/poker/flopEquity.ts"), file);
      console.log(`Wrote ${jobs.length} flop equities in ${((Date.now() - started) / 1000).toFixed(0)}s`);
    });
    worker.on("error", (e) => {
      console.error(e);
      process.exit(1);
    });
  }
} else {
  const chunk = workerData as [number, number][];
  parentPort!.postMessage(chunk.map(([s, f]) => [s, f, equity(FLOP_SPOTS[s], f)]));
}
