/**
 * Precomputes all-in preflop equity for every pair of the 169 starting-hand classes
 * and writes src/poker/preflopEquity.ts.
 *
 * Each matchup samples SAMPLES random deals: a concrete combo for each class that
 * shares no cards, then a random five-card board. Standard error is about
 * 0.5 / sqrt(SAMPLES), well under one percent.
 *
 * Run with: npm run build:equity
 */
import { writeFileSync } from "node:fs";
import { cpus } from "node:os";
import { resolve } from "node:path";
import { isMainThread, parentPort, Worker, workerData } from "node:worker_threads";
import { fileURLToPath } from "node:url";
import { type Card, cardCode, fullDeck } from "../src/poker/cards";
import { score7 } from "../src/poker/evaluator";
import { classCombos, encodeEquity, HAND_CLASSES } from "../src/poker/preflop";

const SAMPLES = Number(process.env.SAMPLES) || 3000;
const N = HAND_CLASSES.length;

function randomInt(n: number) {
  return Math.floor(Math.random() * n);
}

/** Hero's equity (win + tie/2) for class i against class j. */
function matchupEquity(i: number, j: number): number {
  const heroCombos = classCombos(HAND_CLASSES[i]);
  const villainCombos = classCombos(HAND_CLASSES[j]);
  const deck = fullDeck();
  let total = 0;
  let done = 0;
  while (done < SAMPLES) {
    const hero = heroCombos[randomInt(heroCombos.length)];
    const villain = villainCombos[randomInt(villainCombos.length)];
    const used = new Set([...hero, ...villain].map(cardCode));
    if (used.size < 4) continue;

    const rest: Card[] = deck.filter((c) => !used.has(cardCode(c)));
    for (let k = 0; k < 5; k++) {
      const r = k + randomInt(rest.length - k);
      [rest[k], rest[r]] = [rest[r], rest[k]];
    }
    const board = rest.slice(0, 5);
    const diff = score7([...hero, ...board]) - score7([...villain, ...board]);
    total += diff > 0 ? 1 : diff === 0 ? 0.5 : 0;
    done++;
  }
  return total / SAMPLES;
}

if (isMainThread) {
  const workers = Math.max(1, cpus().length);
  const table = new Float64Array(N * N);
  const pairs: [number, number][] = [];
  for (let i = 0; i < N; i++) for (let j = i; j < N; j++) pairs.push([i, j]);
  const chunks = Array.from({ length: workers }, (_, w) => pairs.filter((_, k) => k % workers === w));

  const started = Date.now();
  let finished = 0;
  const self = fileURLToPath(import.meta.url);
  chunks.forEach((chunk) => {
    const worker = new Worker(self, { workerData: chunk });
    worker.on("message", (results: [number, number, number][]) => {
      for (const [i, j, eq] of results) {
        table[i * N + j] = eq;
        table[j * N + i] = i === j ? eq : 1 - eq;
      }
      if (++finished === workers) {
        const encoded = Array.from(table, encodeEquity).join("");
        const file = `// Generated by scripts/build-preflop-equity.ts. Do not edit by hand.
// All-in preflop equity for every pair of the 169 hand classes, ${SAMPLES} sampled deals each.
// Row = hero class, column = villain class, in HAND_CLASSES order; two characters per value.
export const PREFLOP_EQUITY_SAMPLES = ${SAMPLES};
export const PREFLOP_EQUITY = "${encoded}";
`;
        writeFileSync(resolve(process.cwd(), "src/poker/preflopEquity.ts"), file);
        console.log(`Wrote ${N * N} equities in ${((Date.now() - started) / 1000).toFixed(0)}s`);
      }
    });
    worker.on("error", (e) => {
      console.error(e);
      process.exit(1);
    });
  });
} else {
  const chunk = workerData as [number, number][];
  parentPort!.postMessage(chunk.map(([i, j]) => [i, j, matchupEquity(i, j)]));
}
